# Imagen base
FROM mysql:latest

# Variables de entorno para la configuración de la base de datos
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=accwe-hospital
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=root

# Copiar script SQL de inicialización
#COPY ./init.sql /docker-entrypoint-initdb.d/

